const tweets = [
  {
    id: 1,
    author: "John Doe",
    username: "@johndoe",
    content: "This is my first tweet!",
    timestamp: new Date(),
    avatar: "https://randomuser.me/api/portraits/men/1.jpg",
    // tweetImage: ,
  },
  {
    id: 2,
    author: "Jane Smith",
    username: "@janesmith",
    content: "Just tweeting away!",
    timestamp: new Date("2023-03-03"),
    avatar: "https://randomuser.me/api/portraits/women/2.jpg",
    // tweetImage: ,
  },
  {
    id: 3,
    author: "Bob Johnson",
    username: "@bobjohnson",
    content: "Hello Twitter world!",
    timestamp: new Date("2024-03-03"),
    avatar: "https://randomuser.me/api/portraits/men/3.jpg",
    // tweetImage: ,
  },
  {
    id: 4,
    author: "Emily Brown",
    username: "@emilybrown",
    content: "Tweeting is fun!",
    timestamp: new Date("2024-03-03"),
    avatar: "https://randomuser.me/api/portraits/women/4.jpg",
    // tweetImage: ,
  },
  {
    id: 5,
    author: "Michael Wilson",
    username: "@michaelwilson",
    content: "Hello, Twitterverse!",
    timestamp: new Date("2024-03-03"),
    avatar: "https://randomuser.me/api/portraits/men/5.jpg",
    // tweetImage: ,
  },
  {
    id: 6,
    author: "Sarah Davis",
    username: "@sarahdavis",
    content: "Just tweeted!",
    timestamp: new Date("2024-03-03"),
    avatar: "https://randomuser.me/api/portraits/women/6.jpg",
    // tweetImage: ,
  },
  {
    id: 7,
    author: "David Rodriguez",
    username: "@davidrodriguez",
    content: "Tweeting from sunny California!",
    timestamp: new Date("2024-03-03"),
    avatar: "https://randomuser.me/api/portraits/men/7.jpg",
    // tweetImage: ,
  },
  {
    id: 8,
    author: "Emma Martinez",
    username: "@emmartinez",
    content: "New tweet alert!",
    timestamp: new Date("2024-03-03"),
    avatar: "https://randomuser.me/api/portraits/women/8.jpg",
    // tweetImage: ,
  },
  {
    id: 9,
    author: "William Lee",
    username: "@williamlee",
    content: "Tweeting is addictive!",
    timestamp: new Date("2024-03-03"),
    avatar: "https://randomuser.me/api/portraits/men/9.jpg",
    // tweetImage: ,
  },
  {
    id: 10,
    author: "Olivia Taylor",
    username: "@oliviataylor",
    content: "Just tweeted something profound!",
    timestamp: new Date("2024-03-03"),
    avatar: "https://randomuser.me/api/portraits/women/10.jpg",
    // tweetImage: ,
  },
  {
    id: 11,
    author: "Daniel Brown",
    username: "@danielbrown",
    content: "Hello, Twitter!",
    timestamp: new Date("2024-03-03"),
    avatar: "https://randomuser.me/api/portraits/men/11.jpg",
    // tweetImage: ,
  },
  {
    id: 12,
    author: "Sophia Evans",
    username: "@sophiaevans",
    content: "Just joined Twitter!",
    timestamp: new Date(2023, 3, 1, 22, 12, 37),
    avatar: "https://randomuser.me/api/portraits/women/12.jpg",
    // tweetImage: ,
  },
  {
    id: 13,
    author: "James Garcia",
    username: "@jamesgarcia",
    content: "Tweeting from the Big Apple!",
    timestamp: new Date(2023, 3, 1, 22, 12, 37),
    avatar: "https://randomuser.me/api/portraits/men/13.jpg",
    // tweetImage: ,
  },
  {
    id: 14,
    author: "Isabella Martinez",
    username: "@isabellamartinez",
    content: "Just tweeted my thoughts!",
    timestamp: new Date(2023, 3, 1, 22, 12, 37),
    avatar: "https://randomuser.me/api/portraits/women/14.jpg",
    // tweetImage: ,
  },
  {
    id: 15,
    author: "Michael Taylor",
    username: "@michaeltaylor",
    content: "Tweeting away!",
    timestamp: new Date(2023, 3, 1, 22, 12, 37),
    avatar: "https://randomuser.me/api/portraits/men/15.jpg",
    // tweetImage: ,
  },
  {
    id: 16,
    author: "Ava Wilson",
    username: "@avawilson",
    content: "Just tweeted something interesting!",
    timestamp: new Date(2023, 3, 1, 22, 12, 37),
    avatar: "https://randomuser.me/api/portraits/women/16.jpg",
    // tweetImage: ,
  },
  {
    id: 17,
    author: "Noah Anderson",
    username: "@noahanderson",
    content: "Tweeting from the top of the mountain!",
    timestamp: new Date(2023, 3, 1, 22, 12, 37),
    avatar: "https://randomuser.me/api/portraits/men/17.jpg",
    // tweetImage: ,
  },
  {
    id: 18,
    author: "Mia Thomas",
    username: "@miathomas",
    content: "Just joined Twitter!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/18.jpg",
    // tweetImage: ,
  },
  {
    id: 19,
    author: "Liam Garcia",
    username: "@liamgarcia",
    content: "Tweeting my thoughts!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/19.jpg",
    // tweetImage: ,
  },
  {
    id: 20,
    author: "Charlotte Rodriguez",
    username: "@charlotterodriguez",
    content: "Hello, Twitter world!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/20.jpg",
  },
  {
    id: 21,
    author: "Ethan Martinez",
    username: "@ethanmartinez",
    content: "Just tweeted something!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/21.jpg",
    // tweetImage: ,
  },
  {
    id: 22,
    author: "Amelia Hernandez",
    username: "@ameliahernandez",
    content: "Tweeting from the beach!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/22.jpg",
    // tweetImage: ,
  },
  {
    id: 23,
    author: "Alexander Martinez",
    username: "@alexandermartinez",
    content: "Just tweeted!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/23.jpg",
    // tweetImage: ,
  },
  {
    id: 24,
    author: "Abigail Wright",
    username: "@abigailwright",
    content: "Tweeting is fun!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/24.jpg",
    // tweetImage: ,
  },
  {
    id: 25,
    author: "Logan Thompson",
    username: "@loganthompson",
    content: "Hello, Twitterverse!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/25.jpg",
    // tweetImage: ,
  },

  {
    id: 26,
    author: "Harper White",
    username: "@harperwhite",
    content: "Just tweeted something interesting!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/26.jpg",
    // tweetImage: ,
  },
  {
    id: 27,
    author: "Jackson Martin",
    username: "@jacksonmartin",
    content: "Tweeting from the top of the mountain!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/27.jpg",
    // tweetImage: ,
  },
  {
    id: 28,
    author: "Madison Garcia",
    username: "@madisongarcia",
    content: "Just joined Twitter!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/28.jpg",
    // tweetImage: ,
  },
  {
    id: 29,
    author: "Lincoln Anderson",
    username: "@lincolnanderson",
    content: "Tweeting my thoughts!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/29.jpg",
    // tweetImage: ,
  },
  {
    id: 30,
    author: "Scarlett Thompson",
    username: "@scarlettthompson",
    content: "Hello, Twitter world!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/30.jpg",
    // tweetImage: ,
  },
  {
    id: 31,
    author: "Luke Davis",
    username: "@lukedavis",
    content: "Just tweeted something!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/31.jpg",
    // tweetImage: ,
  },
  {
    id: 32,
    author: "Hannah Johnson",
    username: "@hannahjohnson",
    content: "Tweeting from the beach!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/32.jpg",
    // tweetImage: ,
  },
  {
    id: 33,
    author: "Gabriel Martinez",
    username: "@gabrielmartinez",
    content: "Just tweeted!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/33.jpg",
    // tweetImage: ,
  },
  {
    id: 34,
    author: "Avery Hernandez",
    username: "@averyhernandez",
    content: "Biking is fun!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/34.jpg",
    tweetImage:
      "https://images.unsplash.com/photo-1575548393466-0df1618ba410?q=80&w=987&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 35,
    author: "Oliver Wright",
    username: "@oliverwright",
    content: "Hello, Twitterverse!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/35.jpg",
    // tweetImage: ,
  },

  {
    id: 36,
    author: "Elijah Clark",
    username: "@elijahclark",
    content: "Just tweeted something interesting!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/36.jpg",
    // tweetImage: ,
  },
  {
    id: 37,
    author: "Zoe Garcia",
    username: "@zoegarcia",
    content: "Tweeting from the top of the mountain!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/37.jpg",
    // tweetImage: ,
  },
  {
    id: 38,
    author: "Jackson King",
    username: "@jacksonking",
    content: "Just joined Twitter!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/38.jpg",
    // tweetImage: ,
  },
  {
    id: 39,
    author: "Madison White",
    username: "@madisonwhite",
    content: "Tweeting my thoughts!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/39.jpg",
    // tweetImage: ,
  },
  {
    id: 40,
    author: "Lucas Perez",
    username: "@lucasperez",
    content: "Hello, Twitter world!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/40.jpg",
    // tweetImage: ,
  },
  {
    id: 41,
    author: "Evelyn Turner",
    username: "@evelynturner",
    content: "Just tweeted something!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/41.jpg",
    // tweetImage: ,
  },
  {
    id: 42,
    author: "Jack Campbell",
    username: "@jackcampbell",
    content: "Tweeting from the beach!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/42.jpg",
    // tweetImage: ,
  },
  {
    id: 43,
    author: "Avery Hall",
    username: "@averyhall",
    content: "Just tweeted!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/43.jpg",
    tweetImage:
      "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 44,
    author: "Brooklyn Ward",
    username: "@brooklynward",
    content: "Tweeting is fun!",
    timestamp: new Date(2023, 12, 30),
    avatar: "https://randomuser.me/api/portraits/men/44.jpg",
    // tweetImage: ,
  },
  {
    id: 45,
    author: "Benjamin Foster",
    username: "@benjaminfoster",
    content: "Hello, Twitterverse!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/45.jpg",
    // tweetImage: ,
  },
  {
    id: 46,
    author: "Nora Gonzales",
    username: "@noragonzales",
    content: "Just tweeted something interesting!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/46.jpg",
    // tweetImage: ,
  },
  {
    id: 47,
    author: "Luke Hughes",
    username: "@lukehughes",
    content: "Tweeting from the top of the mountain!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/47.jpg",
    tweetImage:
      "https://images.unsplash.com/photo-1707343848552-893e05dba6ac?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  },
  {
    id: 48,
    author: "Audrey Scott",
    username: "@audreyscott",
    content: "Just joined Twitter!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/48.jpg",
    // tweetImage: ,
  },
  {
    id: 49,
    author: "Hunter Young",
    username: "@hunteryoung",
    content: "Tweeting my thoughts!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/women/49.jpg",
    // tweetImage: ,
  },
  {
    id: 50,
    author: "Scarlett Robinson",
    username: "@scarlettrobinson",
    content: "Hello, Twitter world!",
    timestamp: new Date(2023, 12, 30, 12, 43, 57),
    avatar: "https://randomuser.me/api/portraits/men/50.jpg",
    // tweetImage: ,
  },
];
export default tweets;
